### ISSUE TITLE
Discuss cost data for powers

### ISSUE THREAD

**Issue by filaraujo** [MalekaiProject/crowfall-data#11]
As of right now we currently define power costs as 
`cost: {
    pips: 0,
    resource: 22
  },`

This however become murky when we have multiple resource types for classes, i.e (rangers with energy and arrows).   We should consider updating this to something more flexible for UI consumption.

Suggestions

```cost:  [{ name: "Resource", count: 10}, { name: "Arrow", count: 10}]```
```cost:  { "Resource": 10, "Arrow": 10}```
```cost: { resource: 10, arrows: 10 }```

**Comment by MichaelFedora** [comment]
We talked about it a little in discord and I think we were going to go with the second;
`cost: { resource: 10, arrow: 10 }`

Again we have the issue of having keys that we don't know explicitly, so perhaps we do:
```javascript
resource_cost: 10;
other_cost: [ { name: "Arrow", count: 10 } ]
```

There was also some other discussion about the resource/pips denotation and how they are basically the same but different. I.E. if a power has resource cost and a templar can apply it, it will turn into power cost; we just don't know really how.

**Comment by MichaelFedora** [comment]
This still needs to be done!
