### ISSUE TITLE
Power Data Folder Structure Sorting

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#19]
cc @filaraujo

Some powers have more than one parent; thus we can't keep the current folder-sorting for the power json objects. We should probably move to everything-in-one-folder or put the multiple-parent ones in their own separate folder (if possible).

**Comment by TheScree** [comment]
I could always make a request that they simply eliminate dual-parenthood.

**Comment by MichaelFedora** [comment]
I think it was mainly for retaliate. Otherwise... I know it's possible that they could do it but I don't think there are any other places where that happens.

Retaliate will be race based anyways, so... yeah.

**Comment by filaraujo** [comment]
Dodge, Cancel Combo, Relentless, Second Wind  are good examples of dual parenthood. However I caution this because i have seen Dodge have different tooltips

**Comment by MichaelFedora** [comment]
Relentless is weird, because Destroyer only is allowed on Champion, but Champion by default comes with Relentless... what?

**Comment by MichaelFedora** [comment]
I believe the end result was to move everything to a root /powers folder
