### ISSUE TITLE
Lexicon for Tags System

### ISSUE THREAD

**Issue by TheScree** [MalekaiProject/crowfall-data#27]
//currently...
let lexicon = ["Stealth", "Severe Bleed", "Heal", "Knockdown", "Snare", "Stun", "Suppress", "Poison", "Reveal", "Exposed", "Burning"];

All up for implementing other tags for Powers or Disciplines. Currently, we are parsing tooltips (and discipline stats) for text matches. Eventually, we need to figure out a more extendable system for customized tagging that can survive import.

Please make recommendations on new tags whenever ;)

**Comment by TheScree** [comment]
Lexicon has been updated to as follows....

  let lexicon = [
    "Stealth", "Severe Bleed", "Moderate Bleed", "Bleed", "Heal", "Knock Down",
    "Snare", "Stun", "Suppress", "Poison", "Reveal", "Exposed", "Burning",
    "Blind", "Mortal Strike", "Health Regeneration", "Weapon Break",
    "Armor Break", "Sin", "Black Mantle", "Burrow", "Barrier", "Invulnerable",
    "Root", "Lifesteal", "Righteousness", "Slow", "Severe Corruption",
    "Moderate Corruption", "Corruption", "Movement Speed", "Attack Power",
    "Support Power", "Retribution", "Fire", "Perception", "Electric", "Crushing",
    "Piercing", "Slashing", "Block", "Parry", "Chain", "Retaliate"
  ];

**Comment by MichaelFedora** [comment]
We should move this to a "tags.json" file, imo. Would make it a lot more portable.
