### ISSUE TITLE
Race Redux

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#34]
They seemed to be structured similarly to a discipline now, i.e.:

![guinecean disc](https://i.imgur.com/jnItoyE.png)

This means we need to ad:
- Stats Granted
- Stats Values
- Powers
- Slots Granted

(or differently named fields according to how #33 is resolved)

**Comment by TheScree** [comment]
These are literally Disciplines. which means they should be categorized under Disciplines and not a races API end point.

In essence, we should delete "Races" from our menu options on Crowfall-wiki and just deprecate it/them here.

**Comment by MichaelFedora** [comment]
Let's keep the race menu, but update the API get races and get discs to be able to filter out types.

Race data_type will not be discipline, but it's `type` will be Race.

**Comment by MichaelFedora** [comment]
Solved via 34006e7
