### ISSUE TITLE
Power ID's Specific to Class/Race

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#48]
Currently we are id-ing them as "dodge-cleric" and "retaliate-knight", etc, but with the new race disciplines, as seen here:

![guinecean disc](https://i.imgur.com/jnItoyE.png)

...they are doing "(parent)-name" instead of "name-(parent)". Should we start doing the former instead of the latter?

**Comment by TheScree** [comment]
If "Dodge" is used repeatedly across multiple races/classes, can we not just refer to it as "Dodge" and parent/source it accordingly? Doesn't absolutely need to be unique powers in the game in terms of source, a power might have multiple sources?

**Comment by MichaelFedora** [comment]
It's called dodge but it's a different power implementation (at least in description) iirc

**Comment by TheScree** [comment]
Going to leave this as is, they plan on cleaning up duplicate names in the future so going to take their word that this is actually no longer going to be a thing.
