### ISSUE TITLE
Add slot_type to power data model

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#49]
Moved from #45 

We need to figure out how to implement the slot restriction.

Name wise, we're going with `slot_restriction`. Do we want the flexibility to have a power being restricted to multiple types of slots (i.e. use an array)?

What are the different values?
- all (or `""`)
- primary
- secondary
- ultimate
- "oh crap" or ... what do we call this?
- ...any other slots?

**Comment by filaraujo** [comment]
Basic, movement, right click, left click, stealth, passive, burrow

**Comment by MichaelFedora** [comment]
Let's do this:

- Normal
- Primary
- Secondary
- Dodge (or something)
- Ultimate
- Passive

For slot types on a tray. Also, sidenote, adding a `iframe` Boolean field would be cool too.

**Comment by MichaelFedora** [comment]
So lets go with:
```typescript
class Power {
  // ...
  slot_type: 'normal' | 'primary' | 'secondary' | 'dodge' | 'ultimate' | 'passive';
  tray: string; // either name or empty.
  // it may even need to be v this v, actually
  trays: { source_id: string, name: string }[];
}```

Aaaand we also need to add the trays on the races/classes/etc. Weeee, this is fun!

**Comment by TheScree** [comment]
Okay. Done!

**Comment by MichaelFedora** [comment]
Not done! ;P I can implement this soon if no one objects.

**Comment by TheScree** [comment]
Go for it, but this is low priority ;p

**Comment by TheScree** [comment]
Interestingly, we actually would need this information if we wanted to implement a build-tool. Similarly, we'd need to indicate what type of bar it can show up on 

bar_type: 'survival' | 'combat' | 'ranged' | 'stealth' 

but also possibly the druid bars 'life' | 'death'
