### ISSUE TITLE
Add "trays" to Races/Classes/Disciplines

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#50]
I.E. the power-sources should have, instead of a `powers` field, a `trays` field that also has their name.

Type change:
```typescript
class Class {
  // ...
  // REMOVE
  powers: string[]
  // ADD
  trays: {
    name: string,
    include_categories: string[],
    exclude_categories: string[],
    cost_modifier: number,
    powers: string[]
  }[];
}
```

```typescript
class Powers {
  // ...
  // ADD
  category: string; // i.e. damage, heal, stealth
}
```

There's also a couple other fields needed to be added:
- `include_categories` `,exclude_categories`, and `cost_modifier` which are best described by examples:
  - druid heal tray would have exclude_categories= `['damage']`, cost modifier: -1 (everything gives resource here; no damage powers)
  - druid nuke tray would have exclude_categories= `['heal']`, cost modifier: +1 (everything has a cost here; no heal powers)
  - duelist stealth tray would have include_categories: `['stealth']`, (ONLY stealth here)
  - duelist regular tray would have exclude_categories: `['stealth']` (no stealth-only powers here)

**Comment by TheScree** [comment]
I'm hoping the new tooltip revision will help designate what bars things can go on. If the game doesnt explicitly spell this out, I'm going to close it because I don't think its worth our time to test every single power in the game to see if it can go in every single tray variation.
