### ISSUE TITLE
Implement more Races

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfall-data#51]
![https://imgur.com/MhDdw2m](http://i.imgur.com/MhDdw2m.png)

**Comment by MichaelFedora** [comment]
![https://crowfall.com/wp-content/uploads/2017/07/elkenracial.png](https://crowfall.com/wp-content/uploads/2017/07/elkenracial.png)

**Comment by TheScree** [comment]
Fixed with 5.3.1 data dump
