### ISSUE TITLE
Cleric lists power 'hand-of-gods' when it should list 'hand-of-the-gods'

### ISSUE THREAD

**Issue by Ligraph** [MalekaiProject/crowfall-data#58]
Cleric lists power 'hand-of-gods' when it should list 'hand-of-the-gods'.  If I can figure out how to fork properly I'll fix it in a pull request.

**Comment by TheScree** [comment]
Just do a pull request when you're done, I'll patch it in.

**Comment by Ligraph** [comment]
Should be done.

**Comment by TheScree** [comment]
Fixed with latest PR
