### ISSUE TITLE
Similarly named stats

### ISSUE THREAD

**Issue by Ligraph** [MalekaiProject/crowfall-data#60]
There are a few stats from different disciplines/races with very similar names.  I can't check them myself b/c I don't have crowfall yet.

Far Sight from (discipline) arcane-archer
Far-Sight from (discipline) elven-eyes

rapid-fire-ranger (power) uses arrows instead of arrow for its cost.  Also has a cost of 0???

Elemental Mitigation from (discipline) arcane-archer
Elemental Mitigations from (discipline) bard

Physical Mitigation from (disciplines) rune-caster and standard-bearer
Physical Mitigations from (discipline) secutor

**Comment by TheScree** [comment]
Go ahead and do a PR on this, if you want. Happy to fix any issues you see.

Our malekai.org viewer doesn't do much with the stats-granted portion of this, so its why it's been overlooked as long as it has. I'd expect numerous similar issues to this exist all over the place as a result.
